# Generated by Django 3.1.1 on 2020-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time_to',
            field=models.TimeField(null=True),
        ),
    ]
